### ISSUE TITLE
Style 32 on swift ui

### ISSUE THREAD

**Issue by navyseai** [ninjaprox/LoaderUI#3]
I was wondering if it was possible to add the style 32 from NVActivityIndicator to swift ui its similar to the BallClipRotate but without the pulse

**Comment by Oktosha** [comment]
I'd like to work on this issue.

**Comment by dev-pitcher** [comment]
I'd love to use #32 too

**Comment by Oktosha** [comment]
Okay, so I tried to implement this animation. It's more complicated than just BallClipRotate without the pulse =/ The problem is that it features simultaneous animations with different timing curves (rotation and the changes in the line length) and I couldn't figure out how to make it work in pure SwiftUI :(

So I tried to adapt the original animation with UIViewRepresentable and here is the repo with the result [Oktosha/CircleStrokeSpin](https://github.com/Oktosha/CircleStrokeSpin). This isn't a perfect solution because foregroundColor modifier is not supported but it kinda works and it's the best I could do ¯\_(ツ)_/¯

**Comment by ninjaprox** [comment]
Hi all, good news that the `CircleStrokeSpin` is now available in [0.2.0](https://github.com/ninjaprox/LoaderUI/releases/tag/0.2.0). Check it out!
